CREATE TABLE IF NOT EXISTS projects(
	id INTEGER PRIMARY KEY generated by DEFAULT as identity,
	name text not null check (name <> ''),
	priority integer not null,
	description text,
	delivery_date date not null
);

CREATE Table if not exists tasks(
	id INTEGER PRIMARY KEY generated by DEFAULT as identity,
	name text not null check (name <> ''),
	done boolean,
	projectId integer references projects(id)
);

-- Insert projects
insert into projects(name, priority, description, delivery_date) values 
('Make a web app', 1, 'Using JavaScript', '2021-05-12'),
('Make an app', 2, 'Using dart', '2021-12-21'),
('Make an desktop app', 2, 'Using c++', '2021-12-15')
;

-- Insert tasks
insert into tasks(name,done,projectid) VALUES
('Download vuejs', false, 1),
('Create UI web', false, 1),
('Download react native', false, 2)
;